CREATE DATABASE PolyNames;
USE DATABASE PolyNames;
CREATE TABLE `Partie` (`id` INT NOT NULL AUTO_INCREMENT, `code_numerique` INT NOT NULL, `code_perso` VARCHAR(50) NOT NULL, PRIMARY KEY(`id`));
CREATE TABLE `Role` (`id` INT NOT NULL AUTO_INCREMENT, `role`, PRIMARY KEY(`id`));
CREATE TABLE `Joueur` (`id` INT NOT NULL AUTO_INCREMENT, `nom` VARCHAR(50) NOT NULL, `role` INT NOT NULL, PRIMARY KEY(`id`), CONSTRAINT `fonction` FOREIGN KEY (`role`) REFERENCES `Role` (`id`));
CREATE TABLE `Couleur` (`id` INT NOT NULL AUTO_INCREMENT, `color` VARCHAR(15) NOT NULL, PRIMARY KEY(`id`));
CREATE TABLE `Mot` (`id` INT NOT NULL AUTO_INCREMENT, `mot` VARCHAR(30) NOT NULL, PRIMARY KEY(`id`));
CREATE TABLE `Carte` (`id` INT NOT NULL AUTO_INCREMENT, `mot` VARCHAR(30) NOT NULL, `couleur` INT NOT NULL, PRIMARY KEY(`id`), CONSTRAINT `colorisation` FOREIGN KEY (`couleur`) REFERENCES `Couleur` (`id`));